ALTER TABLE deployments ADD COLUMN IF NOT EXISTS commit_id VARCHAR(255);
ALTER TABLE deployments ADD COLUMN IF NOT EXISTS commit_message TEXT;
ALTER TABLE deployments ADD COLUMN IF NOT EXISTS branch VARCHAR(255);
